### PR TITLE
feat: mobile responsify open orders table

### LINKED ISSUE #738: [DEX] Open order list mobile responsiveness improvements
### **Design**
- [Activity > Spot Orders > Open Orders](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=4242%3A12192)
- [Activity > Derivatives Orders > Open Orders
](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=4254%3A13275)

### **Summary**
Improve mobile responsiveness based on the proposed design
- [ ] {Trade > Open Orders}
- [ ] {Activity > Spot Orders > Open Orders}
- [ ] {Activity > Derivatives Orders > Open Orders}

### PR DESCRIPTION
**Pull request by ThomasRalee**
## This PR:
- resolves #738 
- figma [design](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=4242%3A12192)

## Screenshots:
- ### Spot orders table
| Activty page | Spot Market page |
|--------------|-------------------|
| image | image |

- ### Derivative orders table
| Activty page | Spot Market page |
|--------------|-------------------|
| image | image |

### CODE REVIEW

**Comment by Tofel** [comment]
1. Have we missed the case, when the viewport is wider than 640px, but not wide enough to display all tables? In such case horizontal scrollbar is missing. Let's remove it only once all columns are displayed? (we have the same issue with positions :/)
image
2. Layout crashes a bit, if there are no orders.
image
3. "Wallet history" tab disappears on the narrowest mobile view:
image
vs
image

**Comment by terencetang9** [comment]
@Tofel Regarding point 3, it is intended to be horizontally scrollable in mobile viewport.

**Comment by terencetang9** [comment]
@Tofel @ThomasRalee We didn't have enough design resource to cater to medium viewport design - the horizontally scrollable table can do for now.

**Comment by terencetang9** [comment]
Example of the horizontally scrollable behaviour for the top tabs.

**Comment by Tofel** [comment]
✅

**Review by Tofel — APPROVED** [review]

**Pull request merged**
