### PR TITLE
fix: order book aggregated price level showing 0 price issue

### LINKED ISSUE #402: Aggregated price levels - 0 price
Hey @ThomasRalee, we should never see 0 as a price, the orders are so small and meaningless but they mess with the displayed data here which we somehow need to fix. I'm thinking that if we can't aggregated some price levels into the chosen unit i.e. 100 here we show them aggregated in the best possible unit below i.e. 10 or 1 and then 0.1.

Alternatively if the price level is less than 100 (or a given chosen unit) we just show 1 for all of them.

@cmhchoi can also advise.

image

image

### PR DESCRIPTION
**Pull request by ThomasRalee**
## This PR:
- resolves #402 

## Screenshots:
- ### Tested the implementation using ZRX on a `10` and `1` aggregate, manually enabled `10` for testing on my local machine.
|Aggregate by 0.1 | Aggregate by 1 | Aggregate by 10 |
|----|----|----|
| image | image | image |

### CODE REVIEW

**Comment by bangjelkoski** [comment]
This is not the correct approach IMO, we should show the `minPriceTickSize` instead, regardless of the aggregation.

**Comment by bangjelkoski** [comment]
Even the implementation is wrong, I don't understand the grouping for the second screenshot?

**Comment by cmhchoi** [comment]
Screenshot 2021-11-19 at 4 11 07 PM
Screenshot 2021-11-19 at 4 11 18 PM


Let's use these as example:

If we use min tick size, then when the order book is in 0.1 scale, how do we show those 0.02, 0.03, 0.04 bids? If we show as min tick size, then it would look like:

--- 0.2
--- 0.1
???
--- 0.001

That's why I think using "<0.1" is better

**Comment by bangjelkoski** [comment]
> Screenshot 2021-11-19 at 4 11 07 PM
> 
> Screenshot 2021-11-19 at 4 11 18 PM
> 
> Let's use these as example:
> 
> If we use min tick size, then when the order book is in 0.1 scale, how do we show those 0.02, 0.03, 0.04 bids? If we show as min tick size, then it would look like:
> 
> --- 0.2 --- 0.1 ??? --- 0.001
> 
> That's why I think using "<0.1" is better

okay, but this only makes sense for buys, we should not do it for sells.

**Comment by cmhchoi** [comment]
From display's point of view, we still need it, because it will still have this display problem

--- 0.2 
--- 0.1 
??? 
--- 0.001

In reality, there should be a very, very rare scenario which this would happen. If it does, then most likely the scale of the order book is wrong and we can just remove that scale (i.e. don't let user to choose 10 scale when the price is always less than 10)

**Comment by bangjelkoski** [comment]
> From display's point of view, we still need it, because it will still have this display problem
> 
> --- 0.2 --- 0.1 ??? --- 0.001
> 
> In reality, there should be a very, very rare scenario which this would happen. If it does, then most likely the scale of the order book is wrong and we can just remove that scale (i.e. don't let user to choose 10 scale when the price is always less than 10)

Let's consider removing this because I have never seen such a representation on the order book as we are proposing here now.

**Pull request merged**
